version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: MarinePath
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: DatVy2003
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spring-net

  app:
    build:
      context: .
      dockerfile: src/main/Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://marinepath.c5e0iiuioxbm.us-east-1.rds.amazonaws.com:5432/MarinePath
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: DatVy2003
    depends_on:
      - postgres
    networks:
      - spring-net

networks:
  spring-net:

volumes:
  postgres_data:
